### ISSUE TITLE
1.0.5 - Right Side of Calendar Cutoff

### ISSUE THREAD

**Issue by MNOCFan** [libasys/calendarplus#119]
When viewing calendar in full screen mode (hiding left menu) the calendar gets cutoff on the right side needing the scroll bar on the bottom to move from left to right. Would it be possible to always have the calendar fit horizontally, but ok to only need scroll bars to view vertically? 

Note: I have only tested this issue in Firefox.

**Comment by deMattin** [comment]
Tested in actual chrome and firefox and don't see this issue ...

Edit: But when switching back, there are scollbars in calendar part in firefox!
A reload solves this until next switch/reswitch
But it's really almost nothing cut off - just some pixel scrolling possible.

Edit2: switch/reswitch issue is only in chrome and not in firefox ...

**Comment by MNOCFan** [comment]
Update: If I start hiding my calendars, the issue clears up. As soon as I get to 8 calendars visible, it gets cutoff.

**Comment by libasys** [comment]
8 calendars?! Respect a Lot of stuff! But this is an issue of fullcalendar Script (3rdparty) and wont fixed at the moment! But with next Version (2xx) of fullcalendar this will be fixed!

**Comment by deMattin** [comment]
I think, 8 Kalendars aren't that much:
I'm actually using 6 calendars (+2 shared from other ressources):
- Privat
- Job
- ToDo (it's a good and simple way to use a calendar for this ;))
- Feiertage
- Urlaub
- TV (to remember me on TV events and series)

I never used categories do differ between event types because Categories aren't very usefull in old offficial calendar app of owncloud.
But in calendar+ this is much nicer with these colored category letters and there it can be usefull to use this instead or additional to many calendars.

And btw. the display issue isn't that high priority for my part as a site reload fixes it and so can wait until 2.xx release. ;)

**Comment by libasys** [comment]
fixed in current master 1.0.6, only scrollbar on right side!

**Comment by MNOCFan** [comment]
This looks and feels much better. Thank you.
