### ISSUE TITLE
Future maintenance of calendarplus app

### ISSUE THREAD

**Issue by farson2003** [libasys/calendarplus#12]
@libasys 
Without doubt your app brings some significant improvements to the "standard" app.

An admin always has to consider installing "3rd party apps" carefully before intalling in a productive work environment, especially if both apps ("standard" vs. calendarplus) (as you pointed out elsewhere) are not easily switched in bigger installations.

Hence a very direct question to @libasys , which may be relevant to many admins who are strongly considering installing your calendar app with advanced features:

What kind of plans do you have when it comes to maintaining a well functioning version of your app including future updates and bugfixes?

Can an admin be certain enough that -if installing it tomorrow on OC8.1.- your app will still be usable in the next 1-2 years, also considering the further development of Owncloud core (...Versions 8.2, 8.3.... or even Version 9.x)?

Myself and others would really welcome an honest answer, as future usage has to be carefully considered before introducing your app in a bigger environment.

Thank you

**Comment by libasys** [comment]
Please read this https://github.com/libasys/calendarplus/issues/6 too! Here I explained why this step for me has happend to build an own calendar app! 
For the future, I hope i get maintaining help from other users of the OC community, but if you have a look at the official calendar app there was a very long time no maintenance only bugfixes! ;) 
The main goal of calendar+ for the future is, to get a really stable version running on different systems and databases, and if the issues list is small the next steps will be raised for new features! By the way i am working since OC 4 was released on writing PR's, Bugfixes and apps for the community!

**Comment by farson2003** [comment]
@libasys wrote " I hope i get maintaining help from other users of the OC community".
I sincerely hope that, your app is beautiful and very handy to use compared to the standard app.

That is why I plan to use it. And that is why I try to assess how likely it is that you will provide future maintanance.
