### ISSUE TITLE
DavDroid sync error

### ISSUE THREAD

**Issue by christianWilling** [libasys/calendarplus#172]
All event are 2 hours later on my phone

timezone is MEZ (+2) on phone and in owncloud

**Comment by Mr-HeBo** [comment]
I have the same problem with davdroid and iCal. However, only serial appointments with active reminder!!

**Comment by dcapper** [comment]
I'm noticing this problem as well. Calendar+ is set to EDT (-4) in ownCloud, but all weekly recurring events appear four hours earlier on my Android smartphone and tablet. Unlike the post above, this happens to events that do not have a reminder.

To reproduce this:
– **In Calendar+ in ownCloud, make a new calendar event at 10:00am EDT on Monday morning.** My event is part of a non-default calendar.
– **Set this event to repeat weekly and end on a certain date.** I set my event to end on a Monday two months later.
– **Sync via DavDroid** to an Android device.

Expected result:
– The event would begin at 10:00am on my Android devices' calendar app.

Actual result:
– The event begins at 6:00am on my Android device.

If I edit the event on my smartphone with the Android calendar app and correct the time, this correction is synced to ownCloud and my other Android device. This leads me to believe it is a problem with Calendar+ and not with DavDroid.

**Comment by RafalNiewinski** [comment]
I also have this problem.

In addition, I noticed another regularity.
I'm from Poland and recently we changed daylight saving time from UTC +2 to UTC +1
Events added to my calendar via a web interface before the time change is shifted on the phone about two hours ahead (UTC +2), while the events added after the change of time are offset by 1 hour ahead (UTC +1).

It seems that the web interface saves event time in the local time zone while the device (in this case the phone) reads the date as if it was written always in UTC.

**Comment by RafalNiewinski** [comment]
I connected the computer to the calendar using **Mozilla Thunderbird**.
In a magical way when I chose the option to edit event and then save it without making any changes resulted in a **solution to all problems on the phone**.

From that moment the events began to appear in the correct time frame for all devices.

In addition, it also solved the problem of exceptions. Previously, they were not taken into account. Now the calendar looks fine on all clients.

Of course, **this does not solves our problem**.
I don't know whether this is due to inconsistencies of CalDAV or its incorrect implementation.
From my research it appears that correct for each device are only the events added with Thunderbird.

Adding events in the web interface causes problems on the phone and adding events to the phone causes problems in the web interface.

Event structure generated in Thunderbird **differs significantly** from that generated by the web interface. I do not know which specific markers generates the problem because the difference is large.

**If someone wants I can share both formats or you can try it yourself.**
If I find a little time to analyze the differences in terms of the problems I'll try to do it.

**Comment by RafalNiewinski** [comment]
Fixed ?

**Comment by christianWilling** [comment]
i installed the app new yesterday and now the error is gone so im going to use this app now :)
