### ISSUE TITLE
Can't add new entry

### ISSUE THREAD

**Issue by wm-simon** [libasys/calendarplus#63]
The popup doesn't appear, if i click on a day.

**Comment by Bullnados** [comment]
Some more informations would be nice

**Comment by aquada** [comment]
If I understand it correctly I am having the same problem. When clicking on a day in any scale (day, week, month) a pop up to create an event does not appear. In the day and week table it will highlight a time, but still no pop up so unable to create any new events. 

I'm on 8.1

EDIT: Bizarrely the problem has gone away since logging off and back in again.

**Comment by libasys** [comment]
@Pfeifakopf Please review that issue https://github.com/libasys/calendarplus/issues/7

**Comment by aquada** [comment]
Thanks for that libasys. I had the wrong default calendar selected.

Can I suggest an message to inform users what the problem is?
