### ISSUE TITLE
Only show red time band for current day

### ISSUE THREAD

**Issue by jancborchardt** [libasys/calendarplus#82]
Currently this looks like this:
![capture du 2013-11-01 01-19-24](https://cloud.githubusercontent.com/assets/925062/9207461/1b69e6e0-406e-11e5-9d7b-fc3b34b81c1d.png)

It’s very strange that the red time band is shown full width, since it’s only relevant for the current day. It should only be shown on the current day, especially because then you have another indicator to easily identify it.

**Comment by libasys** [comment]
If you have a look on a desktop calendar app like macs calendar app the redline on week view shows also the complete view, from monday till sunday!

**Comment by MorrisJobke** [comment]
> from monday till sunday!

And it's weird. Because (except from timetraveling) it is not possible to have 7 different times be the current time. Copying bad design isn't a real argument.

Good design of this feature in the google calendar:

![bildschirmfoto von 2015-08-12 11-06-54](https://cloud.githubusercontent.com/assets/245432/9220353/4c5c6d8a-40e2-11e5-9754-cd8f51dc21ff.png)

**Comment by libasys** [comment]
apple bad design, ok it's your opinion! google design of calendar app is for me a little bit to wired!

**Comment by MorrisJobke** [comment]
> apple bad design, ok it's your opinion! google design of calendar app is for me a little bit to wired!

It was only about the red line. Nothing more. And it makes totally sense to only show the red line on the current day, because it should highlight the current time.

**Comment by libasys** [comment]
but this is really a design question! I would like to see the complete redline because the time agenda is on the left side on the calendar and not within the current day!

**Comment by jancborchardt** [comment]
> because the time agenda is on the left side on the calendar and not within the current day!

In that case we could show a small line of red also in the time column. But having it span over the whole week is very confusing.

For reference, this is the full iCloud calendar design:
![capture du 2015-08-12 11-24-28](https://cloud.githubusercontent.com/assets/925062/9220725/d5ef21f8-40e4-11e5-8605-29605c9197fb.png)
They show the exact time in the left sidebar, plus a red dot on the current day, and they highlight the current day header in red as well. I’m not saying we should do all that, just what I mentioned above.

**Comment by libasys** [comment]
Ok i tried it and it looks cool with the ball and the excat time.
![tiemline](https://cloud.githubusercontent.com/assets/2439975/9228916/f78bc434-411a-11e5-9ce8-721e464c6bf2.jpg)

Working on http://demo81.libasyscloud.de

**Comment by jancborchardt** [comment]
@libasys cool! I’d still stay that the line shouldn’t go through the full width because that’s very confusing. I was not calling for copying the complete design of iCal. ;)

**Comment by libasys** [comment]
it wasn't much work! ;)

**Comment by farson2003** [comment]
I would suggest not only a ball. It would make it more intuitive to see "where I am" timewise if it was more like here Idea based on Baikal2 development: See demo here: http://baikal2.scalingo.io/login:

![present time of day](https://cloud.githubusercontent.com/assets/3358665/9354836/a1c87bfe-466b-11e5-850f-c4f67fc313cf.png)

In words: The ball is a little small. Add a little thick line. 
Thats my opinion. I am sure that is not the most important issue here, but if it is not too difficult to do...

**Comment by jancborchardt** [comment]
Folks – we’re just adding stuff on top of already existing stuff to make the important things stand out. Think about a minimal solution. Showing the line only on the current day makes sense because it’s only relevant for this day, and also makes it clear which day is the current one …
Of curse additionally the current time can be shown in the left sidebar.

**Comment by Bullnados** [comment]
I like the line and bubble implementation. :+1: 
You orient oneself at once, seeing actual time and date.
The baikal line for actual day is confusing/bad noticeable.:-1:
But I agree with @ffarson2003 karger bubble would be nice.
And now let bubbles beeing bubbles :smile: and focus in more important things

**Comment by deMattin** [comment]
I fully agree with @jancborchardt's proposal.
The red line through all days is the first thing, that irritated me after activating the app in week view.
It's neither intuitive nor logical to show this line in previous and following days!

**Comment by Bullnados** [comment]
Stop nugling and pls show better alternatives with same information grade

**Comment by deMattin** [comment]
Me and dictionary don't know, what you mean with "[nugling](http://www.urbandictionary.com/define.php?term=Nugle)" - so I don't know, what to stop.

I mentioned that a line or "actual marker" should be in actual day and that's logical and intuitive without comparing with other apps or used views from other platforms.
So a time marker like in the official app or @MorrisJobke showed is a more intuitive solution in my opinion and I asked another "only user of this", too.
Why showing a marker that seems to be valid or shown for all days in week view?
(Marking of the current day is not working in rework branch for saturdays).

This line through all days and dot is a working compromise and without dot it's more irritating and without a daymarker much more.
The dot shouldn't use a reserved aligning space for it and so it shouldn't reduce the space for calendar entries!

I see no really need to see the real time in numbers in calendar for this visualisation of actual time, but here other perspectives may exist - but you don't need a "through all days" line for that.

I tell you the users sight, (first) impression of a look and my thoughts about solutions - this is my "job" here, not the coding. If this is "nugling", I won't stop it.

So my proposal (without coding):
- Red line in actual day with dot marker on the left of actual day in layer behind the calendar events (this is the reason for the dot, because without it, your line marker has to be hidden, if an event is active on actual time)
- red actual time "in numbers" in the timeline on the left
  ![1](https://cloud.githubusercontent.com/assets/5565503/9423856/15486a18-48d7-11e5-88fc-e8dc25b89c37.png)
  ![2](https://cloud.githubusercontent.com/assets/5565503/9423857/178ede2e-48d7-11e5-9fdf-f82f310877c1.png)

Or what's about to show the time in actual day instead of the left side?
I think, it's no problem, that actual time will and should be overlayed by an active event you already missed. ;)
![3](https://cloud.githubusercontent.com/assets/5565503/9423873/23529542-48d8-11e5-8c8a-4d194886cc59.png)
I really like this:
- intuitive
- no problem with collision (readability) of actual time hitting fixed time markers like if displayed on the left
- information (time) is where you are looking at (actual position of day)
- looks smooth and well in my opinion
- actual time and marker is noticeable ...

**Comment by jancborchardt** [comment]
@deMattin yeeah man, nice mockups! :) Your first one is exactly what I meant.
(I wouldn’t do the second one since there the time text would possibly overlap with events, and the exact current time is not _that_ important.)

**Comment by libasys** [comment]
is integrated on the new version (1.0.4) master!

**Comment by jancborchardt** [comment]
@libasys cool, thanks a ton! :)

**Comment by Bullnados** [comment]
@deMattin love autocorrect i meant NAG 😊. Your mockups are nice.
Back from holidays.
